Correct recognition of way to etc. Support Mandriva and Mandrake Linux. Optioned of library libwrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,16 +6,6 @@
 # Установим рабочие переменные
 UNAME=`uname`
 
-# Переменную $LANG - берём из настройки локали.
-if [ -f ./lang/$LANG ]; then
-    . ./lang/$LANG
-elif [ -f ./lang/en_US ]; then
-    . ./lang/en_US
-else
-    echo "Can't open language file"
-    exit 1
-fi
-
 # Проверим наличие необходимых системных утулит.
 checksysutils(){
     if [ "$UNAME" = "Linux" -o "$LINUXYES" = "YES" ];then
@@ -23,7 +13,7 @@ checksysutils(){
     else
 	MD5_PRG=md5
     fi
-    for ac_prg in sed awk head [ expr $MD5_PRG urandom printf
+    for ac_prg in sed awk head [ expr $MD5_PRG urandom printf mkdir cp ls rm find
     do
 	echo -n "checking if system file \"$ac_prg\" is existing: "
 	for ac_dir in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin /dev
@@ -38,7 +28,7 @@ checksysutils(){
 	done
 	if [ $FILE_NOT_EXISTS -ne 0 ]; then
 	    echo "NONE"
-	    echo "configure aborting!"
+	    echo "configure aborted!"
 	    exit 1
 	fi
     done
@@ -55,7 +45,18 @@ passwordgen(){
     fi
 }
 
+# Переменную $LANG - берём из настройки локали.
+if [ -f ./lang/$LANG ]; then
+    . ./lang/$LANG
+elif [ -f ./lang/en_US ]; then
+    . ./lang/en_US
+else
+    echo "Can't open language file"
+    exit 1
+fi
+
 UPDATEQUESTION="YES"
+DISABLE_LIBWRAP="NO"
 
 for i
 do
@@ -63,28 +64,37 @@ do
 	"--help")
 	    HELP="yes"
 	;;
-	"--disable-update")
+	--disable-update=[Yy][Ee][Ss])
 	    UPDATEQUESTION="NO"
+	;;
+	--disable-libwrap=[Yy][Ee][Ss])
+	    DISABLE_LIBWRAP="YES"
 	;;
 	--linux-version=*)
 	    case "$1" in
 	        "--linux-version=SuSE")
-		    LINUXVERSVION="suse"
+		    LINUXVERSION="suse"
 	        ;;
 	        "--linux-version=RedHat")
-	    	    LINUXVERSVION="redhat"
+	    	    LINUXVERSION="redhat"
 		;;
 		"--linux-version=ASPlinux")
-		    LINUXVERSVION="asplinux"
+		    LINUXVERSION="asplinux"
 		;;
 		"--linux-version=ALTlinux")
-		    LINUXVERSVION="altlinux"
+		    LINUXVERSION="altlinux"
+		;;
+		"--linux-version=Mandriva")
+		    LINUXVERSION="mandriva"
 		;;
 	    esac                        
 	    LINUXYES="YES"	    
 	;;
 	--prefix=*)
 	    PREFIX=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+	--etc-prefix=*)
+	    ETC_PREFX=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
 	;;
 	--with-perl=*)
 	    PERL=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
@@ -118,9 +128,31 @@ then
     fi
 fi
 
-if [ "$PREFIX" = "/" ];then
-    TRUEPREFIX=$PREFIX
-    NOTCONTINUEPREFIX=YES
+# Check for last slash "/" in the PREFIX
+# Проверка на завершающий слеш "/" в переменной PREFIX
+SUFIX=$(expr 0$PREFIX : 0".*\(\/\)\$")
+while [ "$SUFIX" = "/" ] ;do
+    PREFIX=$(expr 0$PREFIX : 0"\(.*\)/\$")
+    SUFIX=$(expr 0$PREFIX : 0".*\(\/\)\$")
+done
+
+if [ -z "$ETC_PREFX" ]
+then
+    if [ "$UNAME" = "Linux" -o "$LINUXYES" = "YES" ];then
+	if [ "$PREFIX" != "/usr" ]
+	then                            
+	    ETC_PREFX=${PREFIX}"/etc"
+	else
+	    ETC_PREFX="/etc"
+	fi
+    else
+	if [ "$PREFIX" != "/usr/local" ]
+	then                            
+	    ETC_PREFX=${PREFIX}"/etc"
+	else
+	    ETC_PREFX="/usr/local/etc"
+	fi
+    fi
 fi
 
 echo "Usage: configure [options]
@@ -131,27 +163,13 @@ Configuration:"
 # Call to function
 checksysutils
 
-# Check for last slash "/" in the PREFIX
-# Проверка на завершающий слеш "/" в переменной PREFIX
-SUFIX=$(expr 0$PREFIX : 0".*\(\/\)\$")
-while [ "$SUFIX" = "/" ] ;do
-    PREFIX=$(expr 0$PREFIX : 0"\(.*\)/\$")
-    SUFIX=$(expr 0$PREFIX : 0".*\(\/\)\$")
-done
-
-if [ "$NOTCONTINUEPREFIX" != "YES" ];then
-    TRUEPREFIX=$PREFIX
-fi
-
-
 if [ -z "$PERL" ]
 then
     PERL="/usr/bin/perl"
 fi
 
-
 if [ "$HELP" = "yes" ];then
-    printf "$msg45" $PREFIX $PREFIX $PREFIX $PERL
+    printf "$msg45" $ETC_PREFX $ETC_PREFX $PREFIX $ETC_PREFX $PERL
     exit 0
 fi
 
@@ -167,8 +185,31 @@ else
     exit 1
 fi
 
+# Создадим директорию для файлов сборки
+echo making temporally dir ./tmp
+if [ ! -d ./tmp ];then
+    mkdir ./tmp
+fi
 
-echo checking for PREFIX path $TRUEPREFIX
+# Начнём лог файл скрипта configure
+echo -n > ./tmp/configure.log
+
+# Копируем все файлы для дальнейших манипуляций над ними.
+echo $msg46
+for cur_files in `ls`
+do
+    if [ "$cur_files" != "tmp" ]; then
+        cp -R ./$cur_files ./tmp
+    fi
+done
+rm ./tmp/Makefile
+rm ./tmp/configure
+rm ./tmp/atslogsetup
+find ./tmp \( -name ".svn" -or -name "CVS" \) -exec rm -rf {} ';' 1>>./tmp/configure.log 2>>./tmp/configure.log
+
+echo checking for PREFIX path $PREFIX
+
+echo checking for ETC_PREFX path $ETC_PREFX
 
 # Установим рабочие переменные
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:.
@@ -185,30 +226,33 @@ if [ "$UNAME" = "Linux" -o "$LINUXYES" = "YES" ];then
     dailyscript=/etc/cron.daily/atslogdaily
     port=ttyS0
 # Определимся с релизом Linux:
-    if [ ! "$LINUXVERSVION" = "" ];then
-	cp ./Linux/atslogdinit.$LINUXVERSVION ./atslogdinit.out
+    if [ ! "$LINUXVERSION" = "" ];then
+	cp ./rc.d/Linux/atslogdinit.$LINUXVERSION ./tmp/rc.d/atslogdinit.tmp
     else
-        if [ -r  /etc/redhat-release ];then
+	if [ -r /etc/mandrake-release -o -r /etc/mandrakelinux-release -o -r /etc/mandriva-release ];then
+# Mandriva
+	    LINUXVERSION="mandriva"
+        elif [ -r  /etc/redhat-release ];then
 # RedHat
-	    LINUXVERSVION="redhat"
+	    LINUXVERSION="redhat"
 	elif [ -r /etc/asplinux-release ];then
 # ASP-Linux
-	    LINUXVERSVION="asplinux"
+	    LINUXVERSION="asplinux"
 	elif [ -r /etc/altlinux-release ];then
 # ALT Linux
-	    LINUXVERSVION="altlinux"
+	    LINUXVERSION="altlinux"
 	elif [ -r /etc/SuSE-release ];then
 # SuSE
-	    LINUXVERSVION="suse"
+	    LINUXVERSION="suse"
 	else
 # Для других версий Linux, кроме перечисленных выше
-	    LINUXVERSVION="redhat"
+	    LINUXVERSION="redhat"
 	fi
     fi
-    cp ./Linux/atslogdinit.$LINUXVERSVION ./atslogdinit.out
+    cp ./rc.d/Linux/atslogdinit.$LINUXVERSION ./tmp/rc.d/atslogdinit.tmp
 else
 # Все другие операционные системы кроме Linux.
-    cp ./FreeBSD/atslogdinit.sh ./atslogdinit.out
+    cp ./rc.d/FreeBSD/atslogdinit.sh ./tmp/rc.d/atslogdinit.tmp
 fi
 
 # Заменим PREFIX
@@ -232,15 +276,15 @@ echo checking for initscript path $initscript
 
 
 # Проверим есть ли в системе старые версии конфигурационных файлов
-echo -n "checking for old config files: "
-if [ -r $PREFIX/etc/panalog.conf ]; then
+echo -n "checking for old config files:"
+if [ -r $ETC_PREFX/panalog.conf ]; then
     if [ "$UPDATEQUESTION" = "YES" ];then
 	UPDATE="YES"
 	CONFONE="YES"
     fi
 fi
 
-if [ -r $PREFIX/etc/atslog.conf ]; then
+if [ -r $ETC_PREFX/atslog.conf ]; then
     if [ "$UPDATEQUESTION" = "YES" ];then
 	UPDATE="YES"
 	CONFTWO="YES"
@@ -250,10 +294,10 @@ fi
 if [ "$CONFONE" = "YES" -o "$CONFTWO" = "YES" ];then
     echo " OK"
 	if [ "$CONFONE" = "YES" ];then
-	    echo $msg36
+	    printf "$msg36" $ETC_PREFX
 	fi
 	if [ "$CONFTWO" = "YES" ];then
-	    echo $msg37
+	    printf "$msg37" $ETC_PREFX
 	fi
 else
     echo " NONE"
@@ -264,13 +308,13 @@ echo checking for Perl path $PERL
 case "$UPDATE" in
 [Yy][Ee][Ss])
     echo $msg38
-	if [ -r $PREFIX/etc/panalog.conf ]; then
+	if [ -r $ETC_PREFX/panalog.conf ]; then
 	    SHAREDIR=$sharedir
 	    MASTERSCRIPT=$masterscript
 	    CLEARDB=$cleardb
 	    PIDFILE=$pidfile
 
-	    . $PREFIX/etc/panalog.conf
+	    . $ETC_PREFX/panalog.conf
 
 	    port=`basename $port`    
 	    callslogfile=`basename $callslogfile`
@@ -281,8 +325,8 @@ case "$UPDATE" in
 	    pidfile=$PIDFILE
 	fi
 
-	if [ -r $PREFIX/etc/atslog.conf ]; then
-	    . $PREFIX/etc/atslog.conf
+	if [ -r $ETC_PREFX/atslog.conf ]; then
+	    . $ETC_PREFX/atslog.conf
 	    if [ -z "$sqlmaspasswd" ];then
 	        sqlmaspasswd=$sqlpassword
 	    fi
@@ -304,7 +348,7 @@ case "$UPDATE" in
     ;;
     *)
 	echo $msg39
-	echo -n "checking for PostgreSQL database: "
+	echo -n "checking for installed PostgreSQL database: "
 	if [ "$MYSQLBASE" != "yes" ];then
 	    if [ -x $PGSQLPATH ];then
 		sqltype=PostgreSQL
@@ -320,14 +364,22 @@ case "$UPDATE" in
 		    SQLTYPE=pgsql
 		    echo OPTIONED
 		else
-		    echo NONE
+		    echo NOT INSTALLED
+# Проверим сервер баз данных, записанный в конфигурационном файле, и назначим
+# значения по молчанию.
+		    if [ "$sqltype" = "PostgreSQL" ];then
+            		SQLTYPE=pgsql
+		    else
+			SQLTYPE=mysql
+		    sqltype=MySQL
+		    fi
 		fi
 	    fi
 	else
 	    echo "NOT USED"
 	fi
 
-	echo -n "checking for MySQL database: "
+	echo -n "checking for installed MySQL database: "
 	if [ "$PGSQLBASE" != "yes" ];then
 	    if [ -x $MYSQLPATH ];then
 		sqltype=MySQL
@@ -343,7 +395,15 @@ case "$UPDATE" in
 		    SQLTYPE=mysql
 		    echo OPTIONED
 		else
-		    echo NONE
+		    echo NOT INSTALLED
+# Проверим сервер баз данных, записанный в конфигурационном файле, и назначим
+# значения по молчанию.
+		    if [ "$sqltype" = "PostgreSQL" ];then
+            		SQLTYPE=pgsql
+		    else
+			SQLTYPE=mysql
+		    sqltype=MySQL
+		    fi
 		fi
 	    fi
 	else
@@ -393,8 +453,12 @@ else
     fi
 fi
 
+if [ "$LINUXVERSION" = "mandriva" ];then
+    LIBNSL=" -lnsl"
+fi
+
 if [ "$UNAME" = "Linux" -o "$LINUXYES" = "YES" ];then
-    echo checking for Linux version is: $LINUXVERSVION
+    echo checking for Linux version is: $LINUXVERSION
 fi
 
 echo checking for PID file path $pidfile
@@ -415,50 +479,49 @@ fi
  -e "s/sqlmaspasswd=''/sqlmaspasswd='$sqlmaspasswd'/g" \
  -e "s/sqltype=''/sqltype='$sqltype'/g" \
  -e "s/model=''/model='$model'/g" \
- < ./www/atslog/include/set/conf.inc > ./conf.inc
+ < ./www/atslog/include/set/conf.inc > ./tmp/www/atslog/include/set/conf.inc
 
 case "$UPDATE" in
     [Yy][Ee][Ss])
 	if [ 0$build -lt 028 ]  ;then
 	    echo checking for update from build 28
-	    cat ./sql/updateto28.mysql.sql >> ./updatesqltables.mysql.sql.out
+	    cat ./sql/updateto28.mysql.sql >> ./tmp/sql/thisupdatesqltables.mysql.sql.tmp
 	fi
 
 	if [ 0$build -lt 030 ]  ;then
 	    echo checking for update from build 30
-	    cat ./sql/updateto30.mysql.sql >> ./updatesqltables.mysql.sql.out
+	    cat ./sql/updateto30.mysql.sql >> ./tmp/sql/thisupdatesqltables.mysql.sql.tmp
 	fi
 
 	if [ 0$build -lt 034 ]  ;then
 	    echo checking for update from build 34
-	    cat ./sql/updateto34.mysql.sql >> ./updatesqltables.mysql.sql.out
+	    cat ./sql/updateto34.mysql.sql >> ./tmp/sql/thisupdatesqltables.mysql.sql.tmp
 	fi
 
 	if [ 0$build -lt 060 ]  ;then
 	    echo checking for update from build 60
-	    cat ./sql/updateto60.mysql.sql >> ./updatesqltables.mysql.sql.out
+	    cat ./sql/updateto60.mysql.sql >> ./tmp/sql/thisupdatesqltables.mysql.sql.tmp
 	fi
 
 	if [ 0$build -lt 088 ]  ;then
 	    echo checking for update from build 88
-	    cat ./sql/updateto88.mysql.sql >> ./updatesqltables.mysql.sql.out
+	    cat ./sql/updateto88.mysql.sql >> ./tmp/sql/thisupdatesqltables.mysql.sql.tmp
 	fi
 
-	if [ -f ./updatesqltables.$SQLTYPE.sql.out ];then
+	if [ -f ./tmp/sql/thisupdatesqltables.$SQLTYPE.sql.tmp ];then
 	    sed \
 	     -e "s/@sqlmaspasswd@/$sqlmaspasswd/g" \
 	     -e "s/@sqlfromhost@/$sqlfromhost/g" \
 	     -e "s/@sqlmasteruser@/$sqlmasteruser/g" \
 	     -e "s/@sqlhost@/$sqlhost/g" \
 	     -e "s/@sqldatabase@/$sqldatabase/g" \
-	     < ./updatesqltables.$SQLTYPE.sql.out > ./updatesqltables.$SQLTYPE.sql
-
+	     < ./tmp/sql/thisupdatesqltables.$SQLTYPE.sql.tmp > ./tmp/sql/thisupdatesqltables.$SQLTYPE.sql
 	fi
-	if [ -f ./updatesqltables.mysql.sql.out ];then
-	    rm ./updatesqltables.mysql.sql.out
+	if [ -f ./tmp/sql/thisupdatesqltables.mysql.sql.tmp ];then
+	    rm ./tmp/sql/thisupdatesqltables.mysql.sql.tmp
 	fi
-	if [ -f ./updatesqltables.pgsql.sql.out ];then
-	    rm ./updatesqltables.pgsql.sql.out
+	if [ -f ./tmp/sql/thisupdatesqltables.pgsql.sql.tmp ];then
+	    rm ./tmp/sql/thisupdatesqltables.pgsql.sql.tmp
 	fi
 
 	echo $msg41
@@ -471,7 +534,7 @@ case "$UPDATE" in
 	     -e "s/@sqlmasteruser@/$sqlmasteruser/g" \
 	     -e "s/@sqlhost@/$sqlhost/g" \
 	     -e "s/@sqldatabase@/$sqldatabase/g" \
-	     < ./sql/createsqltables.$SQLTYPE.sql > ./createsqltables.$SQLTYPE.sql
+	     < ./sql/createsqltables.$SQLTYPE.sql > ./tmp/sql/thiscreatesqltables.$SQLTYPE.sql
 	fi
 
 	if [ -f ./sql/createuser.$SQLTYPE.sql ];then
@@ -481,7 +544,7 @@ case "$UPDATE" in
 	     -e "s/@sqlmasteruser@/$sqlmasteruser/g" \
 	     -e "s/@sqlhost@/$sqlhost/g" \
 	     -e "s/@sqldatabase@/$sqldatabase/g" \
-	     < ./sql/createuser.$SQLTYPE.sql > ./createuser.$SQLTYPE.sql
+	     < ./sql/createuser.$SQLTYPE.sql > ./tmp/sql/thiscreateuser.$SQLTYPE.sql
 	fi
 
 	echo $msg42
@@ -521,79 +584,121 @@ esac
  -e "s%^pidfile=/var/run/atslogd.pid%pidfile=$pidfile%g" \
  -e "s%^fastwrite=yes%fastwrite=$fastwrite%g" \
  -e "s%^sqltype=MySQL%sqltype=$sqltype%g" \
- < ./include/atslog.conf.default > ./atslog.conf
+ < ./include/atslog.conf.default > ./tmp/include/atslog.conf
 
  echo checking for Perl path in scripts/checkDBD.pl
  sed \
  -e "s%/usr/bin/perl%$PERL%g" \
- < ./scripts/checkDBD.pl > ./scripts/checkDBD.out.pl
- chmod a+x ./scripts/checkDBD.out.pl
+ < ./scripts/checkDBD.pl > ./tmp/scripts/checkDBD.pl
+ chmod a+x ./tmp/scripts/checkDBD.pl
 
  echo checking for Perl path in scripts/createdb.pl
  sed \
  -e "s%/usr/bin/perl%$PERL%g" \
- < ./scripts/createdb.pl > ./scripts/createdb.out.pl
- chmod a+x ./scripts/createdb.out.pl
+ < ./scripts/createdb.pl > ./tmp/scripts/createdb.pl
+ chmod a+x ./tmp/scripts/createdb.pl
 
  echo checking for Perl path in atslogcleardb.pl
  sed \
  -e "s%/usr/bin/perl%$PERL%g" \
- < ./include/atslogcleardb.pl > ./atslogcleardb.pl.out
+ < ./include/atslogcleardb.pl > ./tmp/include/atslogcleardb.pl.tmp
+
  echo checking for config file path in atslogcleardb.pl
  sed \
- -e "s%/usr/local/etc/atslog.conf%$PREFIX/etc/atslog.conf%g" \
- < ./atslogcleardb.pl.out > ./atslogcleardb.pl
- if [ -f ./atslogcleardb.pl.out ];then
-    rm ./atslogcleardb.pl.out
+ -e "s%/usr/local/etc/atslog.conf%$ETC_PREFX/atslog.conf%g" \
+ < ./tmp/include/atslogcleardb.pl.tmp > ./tmp/include/atslogcleardb.pl
+ if [ -f ./tmp/include/atslogcleardb.pl.tmp ];then
+    rm ./tmp/include/atslogcleardb.pl.tmp
  fi
 
  echo checking for Perl path in atslogdb.pl
  sed \
  -e "s%/usr/bin/perl%$PERL%g" \
- < ./include/atslogdb.pl > ./atslogdb.pl.out
+ < ./include/atslogdb.pl > ./tmp/include/atslogdb.pl.tmp
+
  echo checking for config file path in atslogdb.pl
  sed \
- -e "s%/usr/local/etc/atslog.conf%$PREFIX/etc/atslog.conf%g" \
- < ./atslogdb.pl.out > ./atslogdb.pl
- if [ -f ./atslogdb.pl.out ];then
-    rm ./atslogdb.pl.out
+ -e "s%/usr/local/etc/atslog.conf%$ETC_PREFX/atslog.conf%g" \
+ < ./tmp/include/atslogdb.pl.tmp > ./tmp/include/atslogdb.pl
+ if [ -f ./tmp/include/atslogdb.pl.tmp ];then
+    rm ./tmp/include/atslogdb.pl.tmp
  fi
 
  echo checking for config file path in atslogmaster
  sed \
- -e "s%/usr/local/etc/atslog.conf%$PREFIX/etc/atslog.conf%g" \
- < ./include/atslogmaster > ./atslogmaster
+ -e "s%/usr/local/etc/atslog.conf%$ETC_PREFX/atslog.conf%g" \
+ < ./include/atslogmaster > ./tmp/include/atslogmaster
 
  echo checking for config file path in atslogdaily
  sed \
- -e "s%/usr/local/etc/atslog.conf%$PREFIX/etc/atslog.conf%g" \
- < ./include/atslogdaily > ./atslogdaily
+ -e "s%/usr/local/etc/atslog.conf%$ETC_PREFX/atslog.conf%g" \
+ < ./include/atslogdaily > ./tmp/include/atslogdaily
 
  echo checking for config file path in atslogrotate
  sed \
- -e "s%/usr/local/etc/atslog.conf%$PREFIX/etc/atslog.conf%g" \
- < ./include/atslogrotate > ./atslogrotate
+ -e "s%/usr/local/etc/atslog.conf%$ETC_PREFX/atslog.conf%g" \
+ < ./include/atslogrotate > ./tmp/include/atslogrotate
 
  echo checking for PREFIX path in Makefile
  sed \
  -e "s%/usr/local%$PREFIX%g" \
- < ./Makefile > ./Makefile.out
+ < ./Makefile > ./tmp/Makefile
 
  echo checking for PREFIX path in installing script
  sed \
- -e "s%PREFIX=\"/usr/local\"%PREFIX=\"$PREFIX\"%g" \
- < ./installing > ./installing.out
+ -e "s%PREFIX_FROM_CONFIGURE_SCRIPT=/usr/local%PREFIX_FROM_CONFIGURE_SCRIPT=$PREFIX%g" \
+ < ./installing > ./tmp/installing.tmp
+
+ echo checking for ETC_PREFX path in installing script
+ sed \
+ -e "s%ETC_PREFX_FROM_CONFIGURE_SCRIPT=/usr/local/etc%ETC_PREFX_FROM_CONFIGURE_SCRIPT=$ETC_PREFX%g" \
+ < ./tmp/installing.tmp > ./tmp/installing
+ if [ -f ./tmp/installing.tmp ];then
+    rm ./tmp/installing.tmp
+ fi
 
  echo checking for config file path in atslogdinit
  sed \
- -e "s%/usr/local/etc/atslog.conf%$PREFIX/etc/atslog.conf%g" \
- < ./atslogdinit.out > ./atslogdinit
- if [ -f ./atslogdinit.out ];then
-    rm ./atslogdinit.out
+ -e "s%/usr/local/etc/atslog.conf%$ETC_PREFX/atslog.conf%g" \
+ < ./tmp/rc.d/atslogdinit.tmp > ./tmp/rc.d/atslogdinit
+ if [ -f ./tmp/rc.d/atslogdinit.tmp ];then
+    rm ./tmp/rc.d/atslogdinit.tmp
  fi
+
+ echo -n "checking for libwrap: "
+ LIBWRAPTOUSE="LIBWRAP=-lwrap"
+ DEFINELIBWRAPTOUSE="#define USE_LIBWRAP"
+ if [ "$DISABLE_LIBWRAP" = "NO" ];then
+    echo OK
+ else
+    LIBWRAPTOUSE="#LIBWRAP=-lwrap"
+    DEFINELIBWRAPTOUSE="// #define USE_LIBWRAP"
+    echo DO NOT USED
+ fi
+ sed \
+ -e "s%LIBWRAP=-lwrap%${LIBWRAPTOUSE}%g" \
+ < ./src/atslogd/Makefile > ./tmp/src/atslogd/Makefile.tmp
+ sed \
+ -e "s%#define USE_LIBWRAP%${DEFINELIBWRAPTOUSE}%g" \
+ < ./src/atslogd/atslogd.h > ./tmp/src/atslogd/atslogd.h
+
+ echo -n "checking for libnsl: "
+ sed \
+ -e "s%LIBWRAP=-lwrap%LIBWRAP=-lwrap${LIBNSL}%g" \
+ < ./tmp/src/atslogd/Makefile.tmp > ./tmp/src/atslogd/Makefile
+ if [ -f ./tmp/src/atslogd/Makefile.tmp ];then
+    rm ./tmp/src/atslogd/Makefile.tmp
+ fi
+ if [ "$LIBNSL" != "" -a "$DISABLE_LIBWRAP" = "NO" ];then
+    echo NECESSARY 
+ else
+    echo NOT NECESSARY 
+ fi
+
+ 
 # Check for Perl DBI.
     echo -n "checking for DBI $sqltype class for Perl: "
-    ./scripts/checkDBD.out.pl $sqltype 1> /dev/null 2> /dev/null
+    ./tmp/scripts/checkDBD.pl $sqltype 1>>./tmp/configure.log 2>>./tmp/configure.log
     if [ $? -ne 0 ];then
 	echo "ERROR"
 	if [ "$SQLTYPE" = "pgsql" ];then
@@ -607,4 +712,5 @@ esac
     fi
 
 echo "Configure done."
+echo "Configure done." > ./tmp/configure.flag
 exit $?
diff --git a/installing b/installing
--- a/installing
+++ b/installing
@@ -6,6 +6,32 @@
 # Установим рабочие переменные
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:.:$bindir:$sharedir
 UNAME=`uname`
+PREFIX_FROM_CONFIGURE_SCRIPT=/usr/local
+ETC_PREFX_FROM_CONFIGURE_SCRIPT=/usr/local/etc
+
+# Проверим наличие необходимых системных утулит.
+checksysutils(){
+    for ac_prg in printf mkdir cp install chown chmod touch read stty [ dirname
+    do
+	echo -n "checking if system file \"$ac_prg\" is existing: "
+	for ac_dir in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin /dev
+	do
+	    if [ -e "$ac_dir/$ac_prg" ]; then
+	        echo "YES"
+		FILE_NOT_EXISTS=0
+		break;
+	    else
+		FILE_NOT_EXISTS=1
+	    fi
+	done
+	if [ $FILE_NOT_EXISTS -ne 0 ]; then
+	    echo "NONE"
+	    echo "install aborted!"
+	    exit 1
+	fi
+    done
+}
+
 for i
 do
     case "$1" in
@@ -17,7 +43,6 @@ do
 	;;
 	--deinstall)
 	    TODO="deinstall"
-	                  
 	;;
 	--install)
 	    TODO="install"
@@ -25,13 +50,21 @@ do
 	--prefix=*)
 	    PREFIX=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
 	;;
+	--etc-prefix=*)
+	    ETC_PREFX=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
     esac
     shift
 done
 
 if [ -z "$PREFIX" ]
 then
-    PREFIX="/usr/local"
+    PREFIX=$PREFIX_FROM_CONFIGURE_SCRIPT
+fi
+
+if [ -z "$ETC_PREFX" ]
+then
+    ETC_PREFX=$ETC_PREFX_FROM_CONFIGURE_SCRIPT
 fi
 
 if [ -z "$TODO" ]
@@ -39,34 +72,33 @@ then
     HELP="yes"
 fi
 
+# Переменную $LANG - берём из настройки локали.
+if [ -f ./lang/$LANG ]; then
+	. ./lang/$LANG
+    elif [ -f ./lang/en_US ]; then
+	. ./lang/en_US
+    else
+        echo "Can't open language file"
+    exit 1
+fi
+
 echo "Usage: installing [options]
 Options: [defaults in brackets after descriptions]
 Use: installing --help for help."
 
+# Call to function
+checksysutils
+
 if [ "$HELP" = "yes" ];then
-
-echo "
---sqlroot=PASSWORD Пароль пользователя root SQL сервера (не системного
-                   пользователя root). Этот пароль  нужен только для
-		   инсталляции или обновления ATSlog. В дальнейшей работе
-		   не используется.
-
---deinstall        Удаление ATSlog.
-
---install          Установка ATSlog.
-
---prefix=PREFIX    install architecture-independent files in PREFIX
-                    [/usr/local]
-"
+    printf "$msg47" $PREFIX $ETC_PREFX
     exit 0
 fi
 
+
 readpasswd(){
-    echo "Введите пароль для суперпользователя SQL сервера (не для системного"
-    echo "суперпользователя). Этот пароль  нужен только для установки или"
-    echo "обновления ATSlog. В дальнейшей работе он не будет использоваться."
+    printf "$msg48"
     trap 'exit;' 0 1 2 3 15
-    echo -n "Пароль: "
+    echo -n $msg49
     stty -echo
     read sqlrootpassword
     stty echo
@@ -109,8 +141,8 @@ copying(){
         mkdir -p $sharedir/sql
 	chmod 555 $sharedir/sql
     fi
-    if [ ! -d $PREFIX/etc ];then
-        mkdir -p $PREFIX/etc
+    if [ ! -d $ETC_PREFX ];then
+        mkdir -p $ETC_PREFX
     fi
 
     touch $logdir/$callslogfile
@@ -141,60 +173,53 @@ copying(){
 	done
 
 	if [ ! -L /etc/atslog.conf ];then
-	    ln -s $PREFIX/etc/atslog.conf /etc/atslog.conf
+	    ln -s $ETC_PREFX/atslog.conf /etc/atslog.conf
 	fi
     fi
-    if [ "$UNAME" = "FreeBSD" ];then
-	if [ ! -d $PREFIX/etc/rc.d ];then
-	    mkdir -p $PREFIX/etc/rc.d
-	fi                          
-    fi
+    if [ ! -d $ETC_PREFX/rc.d ];then
+        mkdir -p $ETC_PREFX/rc.d
+    fi                          
 
-    install -m 755 ./atslogdinit $initscript
-    install -m 755 ./atslogrotate $monthlyscript
-    install -m 755 ./atslogdaily $dailyscript
-    install -m 755 ./atslogdb.pl $bindir/$atslogdb
-    install -m 600 ./atslog.conf $PREFIX/etc/atslog.conf
-    install -m 644 ./atslog.conf $PREFIX/etc/atslog.conf.default
-    install -m 644 ./atslog.conf $sharedir/atslog.conf.default
-    install -m 644 ./libexec/kx-ta616-308-ru.lib $libdir/kx-ta616-308-ru.lib
-    install -m 644 ./libexec/gd-320.lib $libdir/gd-320.lib
-    install -m 644 ./libexec/gdk-100.lib $libdir/gdk-100.lib
-    install -m 644 ./libexec/ghx-46.lib $libdir/ghx-46.lib
-    install -m 644 ./libexec/skp-816.lib $libdir/skp-816.lib
-    install -m 644 ./libexec/nx-820.lib $libdir/nx-820.lib
-    install -m 644 ./libexec/hicom-350h.lib $libdir/hicom-350h.lib
-    install -m 644 ./libexec/kx-td1232.lib $libdir/kx-td1232.lib
-    install -m 644 ./libexec/kx-td816ru.lib $libdir/kx-td816ru.lib
-    install -m 755 ./src/atslogd/atslogd $bindir/$atslogd
-    install -m 755 ./atslogmaster $bindir/$masterscript
-    install -m 755 ./atslogcleardb.pl $bindir/$cleardb
-    install -m 644 ./installing.out $sharedir/installing
-    install -m 644 ./INSTALL $sharedir/INSTALL
-    install -m 644 ./Makefile.out $sharedir/Makefile
-    install -m 644 ./README $sharedir/README
-    install -m 644 ./DEINSTALL $sharedir/DEINSTALL
-    install -m 644 ./UPDATING $sharedir/UPDATING
-    install -m 644 ./USING $sharedir/USING
-    install -m 644 ./CHANGES $sharedir/CHANGES
-    cp -R textlogs $sharedir
-    cp -R www/* $PREFIX/www
-    cp -R sql/* $sharedir/sql
-    cp -R conf.inc $PREFIX/www/atslog/include/set
+    install -m 755 ./tmp/rc.d/atslogdinit $initscript
+    install -m 755 ./tmp/include/atslogrotate $monthlyscript
+    install -m 755 ./tmp/include/atslogdaily $dailyscript
+    install -m 755 ./tmp/include/atslogdb.pl $bindir/$atslogdb
+    install -m 600 ./tmp/include/atslog.conf $ETC_PREFX/atslog.conf
+    install -m 644 ./tmp/include/atslog.conf $ETC_PREFX/atslog.conf.default
+    install -m 644 ./tmp/include/atslog.conf $sharedir/atslog.conf.default
+
+    install -m 644 ./tmp/libexec/* $libdir/
+
+    install -m 755 ./tmp/src/atslogd/atslogd $bindir/$atslogd
+    install -m 755 ./tmp/include/atslogmaster $bindir/$masterscript
+    install -m 755 ./tmp/include/atslogcleardb.pl $bindir/$cleardb
+    install -m 644 ./tmp/installing $sharedir/installing
+    install -m 644 ./tmp/INSTALL $sharedir/INSTALL
+    install -m 644 ./tmp/Makefile $sharedir/Makefile
+    install -m 644 ./tmp/README $sharedir/README
+    install -m 644 ./tmp/DEINSTALL $sharedir/DEINSTALL
+    install -m 644 ./tmp/UPDATING $sharedir/UPDATING
+    install -m 644 ./tmp/USING $sharedir/USING
+    install -m 644 ./tmp/CHANGES $sharedir/CHANGES
+    cp -R ./tmp/textlogs $sharedir
+    cp -R ./tmp/www/* $PREFIX/www
+    cp -R ./tmp/sql/* $sharedir/sql
     chmod -R a-w,a+rX $PREFIX/www/atslog
-    cp -R lang/* $sharedir/$langdir
+    cp -R ./tmp/lang/* $sharedir/$langdir
 }
 
 case "$TODO" in
 deinstall)
 
 # Start deinstalling
-    if [ -r $PREFIX/etc/atslog.conf ];then
-	. $PREFIX/etc/atslog.conf
+    if [ -r $ETC_PREFX/atslog.conf ];then
+	. $ETC_PREFX/atslog.conf
+    elif [ -r ./tmp/include/atslog.conf ]; then
+    	. ./tmp/include/atslog.conf
+    elif [ -r ./tmp/include/atslog.conf.default ]; then
+    	. ./tmp/include/atslog.conf.default
     elif [ -r ./include/atslog.conf.default ]; then
     	. ./include/atslog.conf.default
-    elif [ -r ./atslog.conf.default ]; then
-    	. ./atslog.conf.default
     else
         echo "Can't open config file."
         exit 1
@@ -213,17 +238,9 @@ deinstall)
     rm $monthlyscript
     rm $dailyscript
     rm $bindir/$atslogdb
-    rm $PREFIX/etc/atslog.conf.default
+    rm $ETC_PREFX/atslog.conf.default
     rm $sharedir/atslog.conf.default
-    rm $libdir/kx-ta616-308-ru.lib
-    rm $libdir/gd-320.lib
-    rm $libdir/gdk-100.lib
-    rm $libdir/ghx-46.lib
-    rm $libdir/skp-816.lib
-    rm $libdir/nx-820.lib
-    rm $libdir/hicom-350h.lib
-    rm $libdir/kx-td1232.lib
-    rm $libdir/kx-td816ru.lib
+    rm $libdir/*
     rm $bindir/$masterscript
     rm $bindir/$atslogd
     rm $bindir/$cleardb
@@ -265,25 +282,28 @@ deinstall)
 	    if [ `ls -1l $PERPATH | grep -c -` = 0 ];then
 		rmdir -p $PERPATH 2> /dev/null
 	    else
-		echo "Директория $PERPATH содержит файлы и не может быть удалена!"
+		printf "$msg50" $PERPATH
 	    fi
 	fi
     done
 
-    echo "Удаление завершено. Не забудьте очистить базы SQL сервера"
+    echo $msg51
     ;;
 install)
 
 # Readin config file
-    if [ -r ./atslog.conf ]; then
-	. ./atslog.conf
+    if [ -r ./tmp/include/atslog.conf ]; then
+	. ./tmp/include/atslog.conf
     else
         echo "Can't open config file. Please start configure."
         exit 1
     fi
 
+# Начнём наш install.log
+echo -n >./tmp/install.log
+
 # Start SQL operations
-    if [ -f updatesqltables.pgsql.sql -o -f createsqltables.pgsql.sql -o -f createuser.pgsql.sql ];then
+    if [ -f ./tmp/sql/thisupdatesqltables.pgsql.sql -o -f ./tmp/sql/thiscreatesqltables.pgsql.sql -o -f ./tmp/sql/thiscreateuser.pgsql.sql ];then
 	SQLTYPE=pgsql
 	sqltype=PostgreSQL
     else
@@ -291,29 +311,29 @@ install)
 	sqltype=MySQL
     fi
 
-    for sqlinfo in createuser.$SQLTYPE.sql createsqltables.$SQLTYPE.sql updatesqltables.$SQLTYPE.sql
+    for sqlinfo in thiscreateuser.$SQLTYPE.sql thiscreatesqltables.$SQLTYPE.sql thisupdatesqltables.$SQLTYPE.sql
     do
-	if [ -f ./$sqlinfo ];then
+	if [ -f ./tmp/sql/$sqlinfo ];then
 	    DBOPERATIONS=true
 	fi
     done
 
     if [ $DBOPERATIONS ];then
-    	echo -n "Проводятся операции с базами данных $sqltype сервера: "
+    	printf "$msg52" $sqltype
     fi
 
     ERROECHO=0
     LASTOPERAT=0
-    for sqlfile in createuser.$SQLTYPE.sql createsqltables.$SQLTYPE.sql updatesqltables.$SQLTYPE.sql
+    for sqlfile in thiscreateuser.$SQLTYPE.sql thiscreatesqltables.$SQLTYPE.sql thisupdatesqltables.$SQLTYPE.sql
     do
-    if [ -f ./$sqlfile ];then
-        if [ "$sqlfile" = "createsqltables.pgsql.sql" ];then
-    	    cat ./$sqlfile | ./scripts/createdb.out.pl $sqlmaspasswd $sqlmasteruser 2>>./install.log
+    if [ -f ./tmp/sql/$sqlfile ];then
+        if [ "$sqlfile" = "thiscreatesqltables.pgsql.sql" ];then
+    	    cat ./tmp/sql/$sqlfile | ./tmp/scripts/createdb.pl $sqlmaspasswd $sqlmasteruser 2>>./tmp/install.log
 	    if [ $? -ne 0 ];then
 		ERROECHO=1
 	    fi
 	else
-	    cat ./$sqlfile | ./scripts/createdb.out.pl 2>>./install.log
+	    cat ./tmp/sql/$sqlfile | ./tmp/scripts/createdb.pl 2>>./tmp/install.log
 	    LASTOPERAT=$?
 	    if [ $LASTOPERAT -eq 1 ];then
 	        ERROECHO=1
@@ -325,9 +345,9 @@ install)
 		    # Call to function
 	    	    readpasswd
 		else
-		    echo -n "Продолжение операций с базами данных: "
+		    echo -n $msg53
 	    	fi
-		cat ./$sqlfile | ./scripts/createdb.out.pl $sqlrootpassword 2>>./install.log
+		cat ./tmp/sql/$sqlfile | ./tmp/scripts/createdb.pl $sqlrootpassword 2>>./tmp/install.log
 		if [ $? -ne 0 ];then
 		    ERROECHO=1
 		fi
@@ -340,23 +360,20 @@ install)
 	if [ $ERROECHO != 1 ];then
     	    echo "OK"
 	else
-    	    echo "ОШИБКА"
+    	    echo $msg54
 	fi
     fi
 
-    echo "Копирование файлов"
+    echo $msg55
 # Call to function
     copying
 
     if [ "$ERROECHO" != "1" ]
     then
-	echo "Установка завершена успешно. Конфигурационный файл $PREFIX/etc/atslog.conf"
+	printf "$msg56" $ETC_PREFX
     else
-	echo "Установка завершена с ошибками. Подробнее смотрите install.log"
-	echo "В результате некоторые действия не были выполнены."
-	echo "Конфигурационный файл $PREFIX/etc/atslog.conf"
+	printf "$msg57" $ETC_PREFX
     fi
     ;;
 esac
-
 exit $?
